on:
  push:
    branches:
      - main
      - fork
    paths:
      - update.mjs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm run update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update'
          file_pattern: README.md
  purge-jsdelivr-cache:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: egad13/purge-jsdelivr-cache@v1
        with:
          attempts: 3
          url: |
            https://cdn.jsdelivr.net/gh/dir/vscode-file-nesting-config@fork/README.md
            https://cdn.jsdelivr.net/gh/dir/vscode-file-nesting-config@latest/README.md
            https://cdn.jsdelivr.net/gh/dir/vscode-file-nesting-config/README.md
